### ISSUE TITLE
hello dear,

### ISSUE THREAD

**Issue by mohanmitkari** [rohitcreoit/flutter_bluetooth_sharing#1]
**when i have click on connect to discovery device showing me this error can you please help me** 

E/MethodChannel#flutter_bluetooth_sharing(27442): Failed to handle method call
E/MethodChannel#flutter_bluetooth_sharing(27442): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
E/MethodChannel#flutter_bluetooth_sharing(27442): 	at com.example.flutter_bluetooth_sharing.FlutterBluetoothSharingPlugin.onMethodCall(FlutterBluetoothSharingPlugin.java:66)
E/MethodChannel#flutter_bluetooth_sharing(27442): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#flutter_bluetooth_sharing(27442): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter_bluetooth_sharing(27442): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter_bluetooth_sharing(27442): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter_bluetooth_sharing(27442): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter_bluetooth_sharing(27442): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_bluetooth_sharing(27442): 	at android.os.Looper.loopOnce(Looper.java:210)
E/MethodChannel#flutter_bluetooth_sharing(27442): 	at android.os.Looper.loop(Looper.java:299)
E/MethodChannel#flutter_bluetooth_sharing(27442): 	at android.app.ActivityThread.main(ActivityThread.java:8319)
E/MethodChannel#flutter_bluetooth_sharing(27442): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_bluetooth_sharing(27442): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/MethodChannel#flutter_bluetooth_sharing(27442): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
I/flutter (27442): Error connecting to device: PlatformException(error, Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
I/flutter (27442): 	at com.example.flutter_bluetooth_sharing.FlutterBluetoothSharingPlugin.onMethodCall(FlutterBluetoothSharingPlugin.java:66)
I/flutter (27442): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
I/flutter (27442): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter (27442): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
I/flutter (27442): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter (27442): 	at android.os.Handler.handleCallback(Handler.java:938)
I/flutter (27442): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (27442): 	at android.os.

**Comment by rohitcreoit** [comment]
@mohanmitkari share your code snippet and also the flutter doctor response
